set( sources
    FS_ArResolver.C
    GEO_FileData.C
    GEO_FileFormat.C
    GEO_FilePrim.C
    GEO_FilePrimAgentUtils.C
    GEO_FilePrimInstancerUtils.C
    GEO_FilePrimUtils.C
    GEO_FilePrimVolumeUtils.C
    GEO_FileProp.C
    GEO_FilePropSource.C
    GEO_FileRefiner.C
    GEO_FileUtils.C
    GEO_HAPIAttribute.C
    GEO_HAPIGeo.C
    GEO_HAPIPart.C
    GEO_HAPIReader.C
    GEO_HAPISessionManager.C
    GEO_HAPIUtils.C
    GEO_HDAFileData.C
    GEO_HDAFileFormat.C
    GEO_SceneDescriptionData.C
    GEO_SharedUtils.C
    HD_DrawModeAdapter.C
    HD_HoudiniRendererPlugin.C
    UHI_GeometryLightAdapter.C
    UHI_HoudiniFieldAssetAdapter.C
)

