set( gusd_sources
    agentUtils.cpp
    attribListsBuilder.cpp
    boundsCache.cpp
    coneWrapper.cpp
    cubeWrapper.cpp
    curvesWrapper.cpp
    cylinderWrapper.cpp
    debugCodes.cpp
    error.cpp
    GEO_IOTranslator.cpp
    groupBaseWrapper.cpp
    gsplatWrapper.cpp
    GT_PackedUSD.cpp
    GT_PointInstancer.cpp
    GT_PrimCache.cpp
    GT_Utils.cpp
    GU_PackedUSD.cpp
    GU_USD.cpp
    instancerWrapper.cpp
    meshWrapper.cpp
    NURBSCurvesWrapper.cpp
    nurbsPatchWrapper.cpp
    OP_ParmChangeMicroNode.cpp
    packedUsdWrapper.cpp
    planeWrapper.cpp
    plugin.cpp
    pointsWrapper.cpp
    primWrapper.cpp
    primvarUtils.cpp
    purpose.cpp
    refiner.cpp
    scopeWrapper.cpp
    shaderWrapper.cpp
    sphereWrapper.cpp
    stageCache.cpp
    stageEdit.cpp
    tetMeshWrapper.cpp
    tokens.cpp
    USD_DataCache.cpp
    USD_StdTraverse.cpp
    USD_ThreadedTraverse.cpp
    USD_Traverse.cpp
    USD_Utils.cpp
    USD_VisCache.cpp
    USD_XformCache.cpp
    UT_TypeTraits.cpp
    writeCtrlFlags.cpp
    xformWrapper.cpp
)

set( gusd_hdk_headers
    api.h
    agentUtils.h
    attribListsBuilder.h
    boundsCache.h
    context.h
    coneWrapper.h
    cubeWrapper.h
    curvesWrapper.h
    cylinderWrapper.h
    debugCodes.h
    defaultArray.h
    error.h
    GEO_IOTranslator.h
    groupBaseWrapper.h
    gsplatWrapper.h
    GT_PackedUSD.h
    GT_PointInstancer.h
    GT_PrimCache.h
    GT_Utils.h
    GT_VtArray.h
    GT_VtStringArray.h
    gusd.h
    GU_PackedUSD.h
    GU_USD.h
    instancerWrapper.h
    meshWrapper.h
    NURBSCurvesWrapper.h
    nurbsPatchWrapper.h
    OP_ParmChangeMicroNode.h
    packedUsdWrapper.h
    planeWrapper.h
    pointsWrapper.h
    primWrapper.h
    primvarUtils.h
    purpose.h
    refiner.h
    scopeWrapper.h
    shaderWrapper.h
    sphereWrapper.h
    stageCache.h
    stageEdit.h
    stageOpts.h
    tetMeshWrapper.h
    tokens.h
    USD_DataCache.h
    USD_PropertyMap.h
    USD_StdTraverse.h
    USD_ThreadedTraverse.h
    USD_Traverse.h
    USD_TraverseSimple.h
    USD_Utils.h
    USD_VisCache.h
    USD_XformCache.h
    UT_Assert.h
    UT_CappedCache.h
    UT_Gf.h
    UT_StaticInit.h
    UT_TypeTraits.h
    UT_Version.h
    writeCtrlFlags.h
    xformWrapper.h
)
