set( sources
    BRAY_HdAOVBuffer.C
    BRAY_HdCamera.C
    BRAY_HdCoordSys.C
    BRAY_HdCurves.C
    BRAY_HdDelegate.C
    BRAY_HdEncodeJSON.C
    BRAY_HdField.C
    BRAY_HdInstancer.C
    BRAY_HdKarma.C
    BRAY_HdLight.C
    BRAY_HdLightFilter.C
    BRAY_HdMaterial.C
    BRAY_HdMaterialNetwork.C
    BRAY_HdMesh.C
    BRAY_HdParam.C
    BRAY_HdPass.C
    BRAY_HdPointPrim.C
    BRAY_HdTokens.C
    BRAY_HdUtil.C
    BRAY_HdVolume.C
)

set( headers
    BRAY_HdAOVBuffer.h
    BRAY_HdCamera.h
    BRAY_HdCoordSys.h
    BRAY_HdCurves.h
    BRAY_HdDelegate.h
    BRAY_HdEncodeJSON.h
    BRAY_HdField.h
    BRAY_HdFormat.h
    BRAY_HdGT.h
    BRAY_HdInstancer.h
    BRAY_HdKarma.h
    BRAY_HdLight.h
    BRAY_HdLightFilter.h
    BRAY_HdMaterial.h
    BRAY_HdMaterialNetwork.h
    BRAY_HdMesh.h
    BRAY_HdParam.h
    BRAY_HdPass.h
    BRAY_HdPointPrim.h
    BRAY_HdTokens.h
    BRAY_HdUtil.h
    BRAY_HdVolume.h
)
