//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(UsdHoudiniHoudiniLayerInfo);
TF_WRAP(UsdHoudiniHoudiniFieldAsset);
TF_WRAP(UsdHoudiniHoudiniMetaCurves);
TF_WRAP(UsdHoudiniHoudiniEditableAPI);
TF_WRAP(UsdHoudiniHoudiniSelectableAPI);
TF_WRAP(UsdHoudiniHoudiniViewportGuideAPI);
TF_WRAP(UsdHoudiniHoudiniCameraPlateAPI);
TF_WRAP(UsdHoudiniHoudiniCanvasCameraAPI);
TF_WRAP(UsdHoudiniHoudiniProceduralAPI);
TF_WRAP(UsdHoudiniHoudiniViewportLightAPI);
TF_WRAP(UsdHoudiniHoudiniApexScene);
TF_WRAP(UsdHoudiniHoudiniApexCharacterBindingAPI);
TF_WRAP(UsdHoudiniHoudiniApexCharacterAPI);
TF_WRAP(UsdHoudiniHoudiniApexShapeBindingAPI);
TF_WRAP(UsdHoudiniHoudiniApexShapeDeformAPI);
TF_WRAP(UsdHoudiniHoudiniApexXformBindingAPI);
TF_WRAP(UsdHoudiniHoudiniLightBarnDoorAPI);
TF_WRAP(UsdHoudiniHoudiniHairDeformAPI);
TF_WRAP(UsdHoudiniHoudiniNodeGraphContainerAPI);
TF_WRAP(UsdHoudiniHoudiniImageFilterList);
TF_WRAP(UsdHoudiniHoudiniImageFilter);
TF_WRAP(UsdHoudiniHoudiniXformCommonAPI);
TF_WRAP(UsdHoudiniTokens);
