//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "./tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdHoudiniTokensType::UsdHoudiniTokensType() :
    albedoscope("albedoscope", TfToken::Immortal),
    all("all", TfToken::Immortal),
    aOVlist("AOVlist", TfToken::Immortal),
    aOVs("AOVs", TfToken::Immortal),
    approximating("approximating", TfToken::Immortal),
    as_solid("as_solid", TfToken::Immortal),
    as_surface("as_surface", TfToken::Immortal),
    barndoorbottom("barndoorbottom", TfToken::Immortal),
    barndoorbottomedge("barndoorbottomedge", TfToken::Immortal),
    barndoorleft("barndoorleft", TfToken::Immortal),
    barndoorleftedge("barndoorleftedge", TfToken::Immortal),
    barndoorright("barndoorright", TfToken::Immortal),
    barndoorrightedge("barndoorrightedge", TfToken::Immortal),
    barndoortop("barndoortop", TfToken::Immortal),
    barndoortopedge("barndoortopedge", TfToken::Immortal),
    bypass("bypass", TfToken::Immortal),
    character("character", TfToken::Immortal),
    character_MultipleApplyTemplate_Binding("character:__INSTANCE_NAME__:binding", TfToken::Immortal),
    character_MultipleApplyTemplate_Rig("character:__INSTANCE_NAME__:rig", TfToken::Immortal),
    color("color", TfToken::Immortal),
    depthscope("depthscope", TfToken::Immortal),
    exponentialbump("exponentialbump", TfToken::Immortal),
    houdiniApexCharacterFiles("houdini:apex:character:files", TfToken::Immortal),
    houdiniApexCharacterRig("houdini:apex:character:rig", TfToken::Immortal),
    houdiniApexDeformJoints("houdini:apex:deform:joints", TfToken::Immortal),
    houdiniApexShape("houdini:apex:shape", TfToken::Immortal),
    houdiniApexShape_MultipleApplyTemplate_Binding("houdini:apex:shape:__INSTANCE_NAME__:binding", TfToken::Immortal),
    houdiniApexShape_MultipleApplyTemplate_Input("houdini:apex:shape:__INSTANCE_NAME__:input", TfToken::Immortal),
    houdiniApexShape_MultipleApplyTemplate_Output("houdini:apex:shape:__INSTANCE_NAME__:output", TfToken::Immortal),
    houdiniApexXform("houdini:apex:xform", TfToken::Immortal),
    houdiniApexXform_MultipleApplyTemplate_Binding("houdini:apex:xform:__INSTANCE_NAME__:binding", TfToken::Immortal),
    houdiniApexXform_MultipleApplyTemplate_Joint("houdini:apex:xform:__INSTANCE_NAME__:joint", TfToken::Immortal),
    houdiniApexXform_MultipleApplyTemplate_Output("houdini:apex:xform:__INSTANCE_NAME__:output", TfToken::Immortal),
    houdiniBackgroundimage("houdini:backgroundimage", TfToken::Immortal),
    houdiniClippingRange("houdini:clippingRange", TfToken::Immortal),
    houdiniContainerInputDisplayColor("houdini:containerInputDisplayColor", TfToken::Immortal),
    houdiniContainerInputPos("houdini:containerInputPos", TfToken::Immortal),
    houdiniContainerOutputDisplayColor("houdini:containerOutputDisplayColor", TfToken::Immortal),
    houdiniContainerOutputPos("houdini:containerOutputPos", TfToken::Immortal),
    houdiniContainerWireStyle("houdini:containerWireStyle", TfToken::Immortal),
    houdiniEditable("houdini:editable", TfToken::Immortal),
    houdiniForegroundimage("houdini:foregroundimage", TfToken::Immortal),
    houdiniGuidescale("houdini:guidescale", TfToken::Immortal),
    houdiniHairdeformCapturemaxpoints("houdini:hairdeform:capturemaxpoints", TfToken::Immortal),
    houdiniHairdeformCaptureminpoints("houdini:hairdeform:captureminpoints", TfToken::Immortal),
    houdiniHairdeformCaptureradius("houdini:hairdeform:captureradius", TfToken::Immortal),
    houdiniHairdeformDeformerPrim("houdini:hairdeform:deformerPrim", TfToken::Immortal),
    houdiniHairdeformDeformmethod("houdini:hairdeform:deformmethod", TfToken::Immortal),
    houdiniHairdeformGsilengthpenaltyscale("houdini:hairdeform:gsilengthpenaltyscale", TfToken::Immortal),
    houdiniHairdeformGsimaxcandidates("houdini:hairdeform:gsimaxcandidates", TfToken::Immortal),
    houdiniHairdeformGsimaxguides("houdini:hairdeform:gsimaxguides", TfToken::Immortal),
    houdiniHairdeformGsiminguides("houdini:hairdeform:gsiminguides", TfToken::Immortal),
    houdiniHairdeformGsinsamples("houdini:hairdeform:gsinsamples", TfToken::Immortal),
    houdiniHairdeformGsisearchradius("houdini:hairdeform:gsisearchradius", TfToken::Immortal),
    houdiniHairdeformGsisigmascale("houdini:hairdeform:gsisigmascale", TfToken::Immortal),
    houdiniHairdeformGsiweightthreshold("houdini:hairdeform:gsiweightthreshold", TfToken::Immortal),
    houdiniHairdeformGuideInterpMeshPrim("houdini:hairdeform:guideInterpMeshPrim", TfToken::Immortal),
    houdiniHairdeformKerneltype("houdini:hairdeform:kerneltype", TfToken::Immortal),
    houdiniHairdeformOrientblend("houdini:hairdeform:orientblend", TfToken::Immortal),
    houdiniHairdeformPreserveclumpsdamping("houdini:hairdeform:preserveclumpsdamping", TfToken::Immortal),
    houdiniHairdeformPreserveclumpsenable("houdini:hairdeform:preserveclumpsenable", TfToken::Immortal),
    houdiniHairdeformPreserveclumpsmaxconstraints("houdini:hairdeform:preserveclumpsmaxconstraints", TfToken::Immortal),
    houdiniHairdeformPreserveclumpsmaxneighbors("houdini:hairdeform:preserveclumpsmaxneighbors", TfToken::Immortal),
    houdiniHairdeformPreserveclumpsstiffness("houdini:hairdeform:preserveclumpsstiffness", TfToken::Immortal),
    houdiniHairdeformPreserveshapeenable("houdini:hairdeform:preserveshapeenable", TfToken::Immortal),
    houdiniHairdeformPreserveshapeiterations("houdini:hairdeform:preserveshapeiterations", TfToken::Immortal),
    houdiniHairdeformPreserveshapekbend("houdini:hairdeform:preserveshapekbend", TfToken::Immortal),
    houdiniHairdeformPreserveshapekstretch("houdini:hairdeform:preserveshapekstretch", TfToken::Immortal),
    houdiniHairdeformPreserveshapelockroots("houdini:hairdeform:preserveshapelockroots", TfToken::Immortal),
    houdiniHairdeformPreserveshaperefposstrength("houdini:hairdeform:preserveshaperefposstrength", TfToken::Immortal),
    houdiniHairdeformSkinPrim("houdini:hairdeform:skinPrim", TfToken::Immortal),
    houdiniHairdeformSmoothcapture("houdini:hairdeform:smoothcapture", TfToken::Immortal),
    houdiniHairdeformSmoothcaptureradius("houdini:hairdeform:smoothcaptureradius", TfToken::Immortal),
    houdiniHairdeformSmoothinglevel("houdini:hairdeform:smoothinglevel", TfToken::Immortal),
    houdiniHairdeformSmoothingmethod("houdini:hairdeform:smoothingmethod", TfToken::Immortal),
    houdiniHairdeformTetmeshtreatment("houdini:hairdeform:tetmeshtreatment", TfToken::Immortal),
    houdiniHairdeformUseorientattrib("houdini:hairdeform:useorientattrib", TfToken::Immortal),
    houdiniInviewermenu("houdini:inviewermenu", TfToken::Immortal),
    houdiniProcedural("houdiniProcedural", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniActive("houdiniProcedural:__INSTANCE_NAME__:houdini:active", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniAnimated("houdiniProcedural:__INSTANCE_NAME__:houdini:animated", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniPriority("houdiniProcedural:__INSTANCE_NAME__:houdini:priority", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralArgs("houdiniProcedural:__INSTANCE_NAME__:houdini:procedural:args", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralPath("houdiniProcedural:__INSTANCE_NAME__:houdini:procedural:path", TfToken::Immortal),
    houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralType("houdiniProcedural:__INSTANCE_NAME__:houdini:procedural:type", TfToken::Immortal),
    houdiniSelectable("houdini:selectable", TfToken::Immortal),
    inheritAnimationLayers("inheritAnimationLayers", TfToken::Immortal),
    inherited("inherited", TfToken::Immortal),
    interpolating("interpolating", TfToken::Immortal),
    linear("linear", TfToken::Immortal),
    list("list", TfToken::Immortal),
    none("none", TfToken::Immortal),
    normalscope("normalscope", TfToken::Immortal),
    orderedFilters("orderedFilters", TfToken::Immortal),
    pivot("pivot", TfToken::Immortal),
    primvarsHoudiniApexDeformJointIndices("primvars:houdini:apex:deform:jointIndices", TfToken::Immortal),
    primvarsHoudiniApexDeformJointWeights("primvars:houdini:apex:deform:jointWeights", TfToken::Immortal),
    quadratic("quadratic", TfToken::Immortal),
    rounded("rounded", TfToken::Immortal),
    sceneFiles("sceneFiles", TfToken::Immortal),
    shear("shear", TfToken::Immortal),
    straight("straight", TfToken::Immortal),
    truncatedgaussian("truncatedgaussian", TfToken::Immortal),
    type("type", TfToken::Immortal),
    HoudiniApexCharacterAPI("HoudiniApexCharacterAPI", TfToken::Immortal),
    HoudiniApexCharacterBindingAPI("HoudiniApexCharacterBindingAPI", TfToken::Immortal),
    HoudiniApexScene("HoudiniApexScene", TfToken::Immortal),
    HoudiniApexShapeBindingAPI("HoudiniApexShapeBindingAPI", TfToken::Immortal),
    HoudiniApexShapeDeformAPI("HoudiniApexShapeDeformAPI", TfToken::Immortal),
    HoudiniApexXformBindingAPI("HoudiniApexXformBindingAPI", TfToken::Immortal),
    HoudiniCameraPlateAPI("HoudiniCameraPlateAPI", TfToken::Immortal),
    HoudiniEditableAPI("HoudiniEditableAPI", TfToken::Immortal),
    HoudiniFieldAsset("HoudiniFieldAsset", TfToken::Immortal),
    HoudiniHairDeformAPI("HoudiniHairDeformAPI", TfToken::Immortal),
    HoudiniImageFilter("HoudiniImageFilter", TfToken::Immortal),
    HoudiniImageFilterList("HoudiniImageFilterList", TfToken::Immortal),
    HoudiniLayerInfo("HoudiniLayerInfo", TfToken::Immortal),
    HoudiniLightBarnDoorAPI("HoudiniLightBarnDoorAPI", TfToken::Immortal),
    HoudiniMetaCurves("HoudiniMetaCurves", TfToken::Immortal),
    HoudiniNodeGraphContainerAPI("HoudiniNodeGraphContainerAPI", TfToken::Immortal),
    HoudiniProceduralAPI("HoudiniProceduralAPI", TfToken::Immortal),
    HoudiniSelectableAPI("HoudiniSelectableAPI", TfToken::Immortal),
    HoudiniViewportGuideAPI("HoudiniViewportGuideAPI", TfToken::Immortal),
    HoudiniViewportLightAPI("HoudiniViewportLightAPI", TfToken::Immortal),
    HoudiniXformCommonAPI("HoudiniXformCommonAPI", TfToken::Immortal),
    allTokens({
        albedoscope,
        all,
        aOVlist,
        aOVs,
        approximating,
        as_solid,
        as_surface,
        barndoorbottom,
        barndoorbottomedge,
        barndoorleft,
        barndoorleftedge,
        barndoorright,
        barndoorrightedge,
        barndoortop,
        barndoortopedge,
        bypass,
        character,
        character_MultipleApplyTemplate_Binding,
        character_MultipleApplyTemplate_Rig,
        color,
        depthscope,
        exponentialbump,
        houdiniApexCharacterFiles,
        houdiniApexCharacterRig,
        houdiniApexDeformJoints,
        houdiniApexShape,
        houdiniApexShape_MultipleApplyTemplate_Binding,
        houdiniApexShape_MultipleApplyTemplate_Input,
        houdiniApexShape_MultipleApplyTemplate_Output,
        houdiniApexXform,
        houdiniApexXform_MultipleApplyTemplate_Binding,
        houdiniApexXform_MultipleApplyTemplate_Joint,
        houdiniApexXform_MultipleApplyTemplate_Output,
        houdiniBackgroundimage,
        houdiniClippingRange,
        houdiniContainerInputDisplayColor,
        houdiniContainerInputPos,
        houdiniContainerOutputDisplayColor,
        houdiniContainerOutputPos,
        houdiniContainerWireStyle,
        houdiniEditable,
        houdiniForegroundimage,
        houdiniGuidescale,
        houdiniHairdeformCapturemaxpoints,
        houdiniHairdeformCaptureminpoints,
        houdiniHairdeformCaptureradius,
        houdiniHairdeformDeformerPrim,
        houdiniHairdeformDeformmethod,
        houdiniHairdeformGsilengthpenaltyscale,
        houdiniHairdeformGsimaxcandidates,
        houdiniHairdeformGsimaxguides,
        houdiniHairdeformGsiminguides,
        houdiniHairdeformGsinsamples,
        houdiniHairdeformGsisearchradius,
        houdiniHairdeformGsisigmascale,
        houdiniHairdeformGsiweightthreshold,
        houdiniHairdeformGuideInterpMeshPrim,
        houdiniHairdeformKerneltype,
        houdiniHairdeformOrientblend,
        houdiniHairdeformPreserveclumpsdamping,
        houdiniHairdeformPreserveclumpsenable,
        houdiniHairdeformPreserveclumpsmaxconstraints,
        houdiniHairdeformPreserveclumpsmaxneighbors,
        houdiniHairdeformPreserveclumpsstiffness,
        houdiniHairdeformPreserveshapeenable,
        houdiniHairdeformPreserveshapeiterations,
        houdiniHairdeformPreserveshapekbend,
        houdiniHairdeformPreserveshapekstretch,
        houdiniHairdeformPreserveshapelockroots,
        houdiniHairdeformPreserveshaperefposstrength,
        houdiniHairdeformSkinPrim,
        houdiniHairdeformSmoothcapture,
        houdiniHairdeformSmoothcaptureradius,
        houdiniHairdeformSmoothinglevel,
        houdiniHairdeformSmoothingmethod,
        houdiniHairdeformTetmeshtreatment,
        houdiniHairdeformUseorientattrib,
        houdiniInviewermenu,
        houdiniProcedural,
        houdiniProcedural_MultipleApplyTemplate_HoudiniActive,
        houdiniProcedural_MultipleApplyTemplate_HoudiniAnimated,
        houdiniProcedural_MultipleApplyTemplate_HoudiniPriority,
        houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralArgs,
        houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralPath,
        houdiniProcedural_MultipleApplyTemplate_HoudiniProceduralType,
        houdiniSelectable,
        inheritAnimationLayers,
        inherited,
        interpolating,
        linear,
        list,
        none,
        normalscope,
        orderedFilters,
        pivot,
        primvarsHoudiniApexDeformJointIndices,
        primvarsHoudiniApexDeformJointWeights,
        quadratic,
        rounded,
        sceneFiles,
        shear,
        straight,
        truncatedgaussian,
        type,
        HoudiniApexCharacterAPI,
        HoudiniApexCharacterBindingAPI,
        HoudiniApexScene,
        HoudiniApexShapeBindingAPI,
        HoudiniApexShapeDeformAPI,
        HoudiniApexXformBindingAPI,
        HoudiniCameraPlateAPI,
        HoudiniEditableAPI,
        HoudiniFieldAsset,
        HoudiniHairDeformAPI,
        HoudiniImageFilter,
        HoudiniImageFilterList,
        HoudiniLayerInfo,
        HoudiniLightBarnDoorAPI,
        HoudiniMetaCurves,
        HoudiniNodeGraphContainerAPI,
        HoudiniProceduralAPI,
        HoudiniSelectableAPI,
        HoudiniViewportGuideAPI,
        HoudiniViewportLightAPI,
        HoudiniXformCommonAPI
    })
{
}

TfStaticData<UsdHoudiniTokensType> UsdHoudiniTokens;

PXR_NAMESPACE_CLOSE_SCOPE
