
#ifndef __USDDUMMY_API_h__
#define __USDDUMMY_API_h__

#include <SYS/SYS_Visibility.h>

#ifdef USDDUMMY_EXPORTS
#define USDDUMMY_API SYS_VISIBILITY_EXPORT
#define USDDUMMY_API_TMPL SYS_VISIBILITY_EXPORT_TMPL
#define USDDUMMY_API_TINST SYS_VISIBILITY_EXPORT_TINST
#else
#define USDDUMMY_API SYS_VISIBILITY_IMPORT
#define USDDUMMY_API_TMPL SYS_VISIBILITY_IMPORT_TMPL
#define USDDUMMY_API_TINST SYS_VISIBILITY_IMPORT_TINST
#endif

#endif
