add_definitions( -DUSDHOUDINI_EXPORTS -DUSDMANTRA_EXPORTS )

set( husd_sources
    HUSD_ApexScene.C
    HUSD_Asset.C
    HUSD_AssetPath.C
    HUSD_BindMaterial.C
    HUSD_Blend.C
    HUSD_ChangeBlock.C
    HUSD_ConfigureLayer.C
    HUSD_ConfigurePrims.C
    HUSD_ConfigureProps.C
    HUSD_Constants.C
    HUSD_CreateMaterial.C
    HUSD_CreatePrims.C
    HUSD_CreateVariants.C
    HUSD_CrowdProcedural.C
    HUSD_Cvex.C
    HUSD_CvexBindingMap.C
    HUSD_CvexCode.C
    HUSD_CvexDataCommand.C
    HUSD_CvexDataInputs.C
    HUSD_DataHandle.C
    HUSD_EditClips.C
    HUSD_EditCollections.C
    HUSD_EditCustomData.C
    HUSD_EditLayers.C
    HUSD_EditLights.C
    HUSD_EditLinkCollections.C
    HUSD_EditMaterial.C
    HUSD_EditReferences.C
    HUSD_EditRelocates.C
    HUSD_EditVariants.C
    HUSD_ErrorScope.C
    HUSD_ExpansionState.C
    HUSD_FileExpanded.C
    HUSD_FindCollections.C
    HUSD_FindPrims.C
    HUSD_FindProps.C
    HUSD_GeoSubset.C
    HUSD_GeoUtils.C
    HUSD_GetAttributes.C
    HUSD_HuskImaging.C
    HUSD_HydraApexSceneEvaluator.C
    HUSD_HydraCamera.C
    HUSD_HydraField.C
    HUSD_HydraGeoPrim.C
    HUSD_HydraLight.C
    HUSD_HydraMaterial.C
    HUSD_HydraPrim.C
    HUSD_Imaging.C
    HUSD_Info.C
    HUSD_LayerCheckpoint.C
    HUSD_LayerOffset.C
    HUSD_LightingMode.C
    HUSD_LoadMasks.C
    HUSD_LockedGeoRegistry.C
    HUSD_LockedStage.C
    HUSD_LockedStageRegistry.C
    HUSD_ManagePrims.C
    HUSD_MaterialUniGraph.C
    HUSD_Merge.C
    HUSD_MergeInto.C
    HUSD_MirrorRootLayer.C
    HUSD_ModifyPaths.C
    HUSD_ObjectHandle.C
    HUSD_ObjectImport.C
    HUSD_ObjectImport-2.0.C
    HUSD_OutputProcessor.C
    HUSD_Overrides.C
    HUSD_Path.C
    HUSD_PathExpression.C
    HUSD_PathPattern.C
    HUSD_PathSet.C
    HUSD_PerfMonAutoCookEvent.C
    HUSD_PointInstancer.C
    HUSD_PointPrim.C
    HUSD_PostLayers.C
    HUSD_Preferences.C
    HUSD_PrimHandle.C
    HUSD_ProjectConfig.C
    HUSD_PropertyHandle.C
    HUSD_Prune.C
    HUSD_PythonConverter.C
    HUSD_RenderBuffer.C
    HUSD_RenderSettings.C
    HUSD_RendererInfo.C
    HUSD_Save.C
    HUSD_Scene.C
    HUSD_SceneDoctor.C
    HUSD_SetAttributes.C
    HUSD_SetMetadata.C
    HUSD_SetRelationships.C
    HUSD_ShaderTranslator.C
    HUSD_Skeleton.C
    HUSD_SpecHandle.C
    HUSD_Stitch.C
    HUSD_TimeCode.C
    HUSD_TimeShift.C
    HUSD_Token.C
    HUSD_UniversalLogUsdSource.C
    HUSD_Utils.C
    HUSD_VexShaderTranslator.C
    HUSD_Xform.C
    HUSD_XformAdjust.C
    HUSD_XformEditor.C
    XUSD_ApexAnimateSceneIndex.C
    XUSD_ApexScene.C
    XUSD_ApexBakeSceneUtils.C
    XUSD_AttributeUtils.C
    XUSD_AutoCollection.C
    XUSD_HdGpMutingSceneIndex.C
    XUSD_Data.C
    XUSD_ExistenceTracker.C
    XUSD_FindPrimsTask.C
    XUSD_HuskTaskManager.C
    XUSD_HydraApexDataSource.C
    XUSD_HydraApexScene.C
    XUSD_HydraCamera.C
    XUSD_HydraExtComputation.C
    XUSD_HydraField.C
    XUSD_HydraGeoImport.C
    XUSD_HydraGeoPrim.C
    XUSD_HydraInstancer.C
    XUSD_HydraLight.C
    XUSD_HydraMaterial.C
    XUSD_HydraUtils.C
    XUSD_ImagingEngine.C
    XUSD_ImagingEngineHusk.C
    XUSD_MirrorRootLayerData.C
    XUSD_OverridesData.C
    XUSD_PathPattern.C
    XUSD_PathSet.C
    XUSD_PropertyAutoCollection.C
    XUSD_RenderSettings.C
    XUSD_RootLayerData.C
    XUSD_ViewerDelegate.C
    XUSD_ShaderRegistry.C
    XUSD_Skeleton.C
    XUSD_LockedGeo.C
    XUSD_LockedGeoRegistry.C
    XUSD_Tokens.C
    XUSD_Utils.C

    UsdHoudini/houdiniApexScene.cpp
    UsdHoudini/houdiniApexCharacterAPI.cpp
    UsdHoudini/houdiniApexCharacterBindingAPI.cpp
    UsdHoudini/houdiniApexShapeBindingAPI.cpp
    UsdHoudini/houdiniApexShapeDeformAPI.cpp
    UsdHoudini/houdiniApexXformBindingAPI.cpp
    UsdHoudini/houdiniCameraPlateAPI.cpp
    UsdHoudini/houdiniEditableAPI.cpp
    UsdHoudini/houdiniHairDeformAPI.cpp
    UsdHoudini/houdiniImageFilter.cpp
    UsdHoudini/houdiniImageFilterList.cpp
    UsdHoudini/houdiniFieldAsset.cpp
    UsdHoudini/houdiniLayerInfo.cpp
    UsdHoudini/houdiniLightBarnDoorAPI.cpp
    UsdHoudini/houdiniMetaCurves.cpp
    UsdHoudini/houdiniProceduralAPI.cpp
    UsdHoudini/houdiniSelectableAPI.cpp
    UsdHoudini/houdiniViewportGuideAPI.cpp
    UsdHoudini/houdiniViewportLightAPI.cpp
    UsdHoudini/houdiniNodeGraphContainerAPI.cpp
    UsdHoudini/houdiniXformCommonAPI.cpp
    UsdHoudini/moduleDeps.cpp
    UsdHoudini/tokens.cpp
)

set( husd_hdk_headers
    HUSD_API.h
    HUSD_ApexScene.h
    HUSD_Asset.h
    HUSD_AssetPath.h
    HUSD_BindMaterial.h
    HUSD_Blend.h
    HUSD_Bucket.h
    HUSD_ChangeBlock.h
    HUSD_Compositor.h
    HUSD_ConfigureLayer.h
    HUSD_ConfigurePrims.h
    HUSD_ConfigureProps.h
    HUSD_Constants.h
    HUSD_CreateMaterial.h
    HUSD_CreatePrims.h
    HUSD_CreateVariants.h
    HUSD_CrowdProcedural.h
    HUSD_Cvex.h
    HUSD_CvexBindingMap.h
    HUSD_CvexCode.h
    HUSD_CvexDataCommand.h
    HUSD_CvexDataInputs.h
    HUSD_DataHandle.h
    HUSD_EditClips.h
    HUSD_EditCollections.h
    HUSD_EditCustomData.h
    HUSD_EditLayers.h
    HUSD_EditLights.h
    HUSD_EditLinkCollections.h
    HUSD_EditMaterial.h
    HUSD_EditReferences.h
    HUSD_EditRelocates.h
    HUSD_EditVariants.h
    HUSD_ErrorScope.h
    HUSD_ExpansionState.h
    HUSD_FileExpanded.h
    HUSD_FindCollections.h
    HUSD_FindPrims.h
    HUSD_FindProps.h
    HUSD_GeoSubset.h
    HUSD_GeoUtils.h
    HUSD_GetAttributes.h
    HUSD_Imaging.h
    HUSD_Info.h
    HUSD_LayerCheckpoint.h
    HUSD_LayerOffset.h
    HUSD_LightingMode.h
    HUSD_LoadMasks.h
    HUSD_LockedGeoRegistry.h
    HUSD_LockedStage.h
    HUSD_LockedStageRegistry.h
    HUSD_ManagePrims.h
    HUSD_MaterialUniGraph.h
    HUSD_Merge.h
    HUSD_MergeInto.h
    HUSD_MirrorRootLayer.h
    HUSD_ModifyPaths.h
    HUSD_ObjectHandle.h
    HUSD_ObjectImport.h
    HUSD_ObjectImport-2.0.h
    HUSD_OutputProcessor.h
    HUSD_Overrides.h
    HUSD_Path.h
    HUSD_PathExpression.h
    HUSD_PathPattern.h
    HUSD_PathSet.h
    HUSD_PerfMonAutoCookEvent.h
    HUSD_PointInstancer.h
    HUSD_PointPrim.h
    HUSD_PostLayers.h
    HUSD_Preferences.h
    HUSD_PrimHandle.h
    HUSD_ProjectConfig.h
    HUSD_PropertyHandle.h
    HUSD_Prune.h
    HUSD_PythonConverter.h
    HUSD_RenderBuffer.h
    HUSD_RendererInfo.h
    HUSD_RenderSettings.h
    HUSD_Save.h
    HUSD_SceneDoctor.h
    HUSD_SetAttributes.h
    HUSD_SetMetadata.h
    HUSD_SetRelationships.h
    HUSD_ShaderTranslator.h
    HUSD_Skeleton.h
    HUSD_SpecHandle.h
    HUSD_Stitch.h
    HUSD_TimeCode.h
    HUSD_TimeShift.h
    HUSD_Token.h
    HUSD_UniversalLogUsdSource.h
    HUSD_Utils.h
    HUSD_VexShaderTranslator.h
    HUSD_Xform.h
    HUSD_XformAdjust.h
    HUSD_XformEditor.h
    XUSD_AttributeUtils.h
    XUSD_AutoCollection.h
    XUSD_HdGpMutingSceneIndex.h
    XUSD_Data.h
    XUSD_DataLock.h
    XUSD_ExistenceTracker.h
    XUSD_FindPrimsTask.h
    XUSD_Format.h
    XUSD_HydraExtComputation.h
    XUSD_HydraInstancer.h
    XUSD_HydraUtils.h
    XUSD_MirrorRootLayerData.h
    XUSD_OverridesData.h
    XUSD_PathPattern.h
    XUSD_PathSet.h
    XUSD_RenderSettings.h
    XUSD_RootLayerData.h
    XUSD_ShaderRegistry.h
    XUSD_LockedGeo.h
    XUSD_LockedGeoRegistry.h
    XUSD_Tokens.h
    XUSD_Utils.h
)

set( husd_internal_headers
    HUSD_HuskImaging.h
    HUSD_HydraApexSceneEvaluator.h
    HUSD_Scene.h
    XUSD_ApexAnimateSceneIndex.h
    XUSD_ApexScene.h
    XUSD_ApexBakeSceneUtils.h
    XUSD_HydraApexDataSource.h
    XUSD_HydraApexScene.h
    XUSD_HydraGeoImport.h
    XUSD_ImagingEngine.h
    XUSD_Skeleton.h
)
