
#ifndef __HUSD_API_h__
#define __HUSD_API_h__

#include <SYS/SYS_Visibility.h>

#ifndef BOOST_NS
#define BOOST_NS hboost
#endif
#define BOOST_HEADER(HEADER_FILE) <BOOST_NS/HEADER_FILE>

#ifdef HUSD_EXPORTS
#define HUSD_API SYS_VISIBILITY_EXPORT
#define HUSD_API_TMPL SYS_VISIBILITY_EXPORT_TMPL
#define HUSD_API_TINST SYS_VISIBILITY_EXPORT_TINST
#else
#define HUSD_API SYS_VISIBILITY_IMPORT
#define HUSD_API_TMPL SYS_VISIBILITY_IMPORT_TMPL
#define HUSD_API_TINST SYS_VISIBILITY_IMPORT_TINST
#endif

#endif
