#ifndef __PRECOMPILED_H__
#define __PRECOMPILED_H__

// Do not edit this file directly.
// Instead, edit $SHM/list_link_libs.py which built this file.
// Then do a 'make precompiled_header' to rebuild precompiled.h.

#include <GU/GU_Detail.h>
#include <IMG/IMG_File.h>
#include <IMG/IMG_Raster.h>
#include <PXL/PXL_Raster.h>
#include <FS/FS_Reader.h>
#include <FS/FS_Writer.h>
#include <UT/UT_Array.h>
#include <UT/UT_ValArray.h>
#include <UT/UT_SmallObject.h>
#include <UT/UT_String.h>
#include <UT/UT_Vector3.h>
#include <UT/UT_Vector4.h>
#include <UT/UT_Matrix3.h>
#include <UT/UT_Matrix4.h>
#include <UT/UT_Map.h>
#include <UT/UT_Set.h>
#include <UT/UT_SymbolTable.h>
#include <UT/UT_UniquePtr.h>
#include <UT/UT_SharedPtr.h>
#include <UT/UT_IntrusivePtr.h>
#include <tools/hpath.h>
#include <SYS/SYS_Math.h>
#include <SYS/SYS_Visibility.h>
#include <tbb/blocked_range.h>
#include <tbb/blocked_range2d.h>
#include <tbb/parallel_for.h>
#include <tbb/parallel_invoke.h>
#include <tbb/parallel_reduce.h>
#include <tbb/scalable_allocator.h>
#include <algorithm>
#include <float.h>
#include <functional>
#include <ieeefp.h>
#include <iostream>
#include <limits.h>
#include <malloc.h>
#include <math.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <vector>

#endif
