set( sources
    HD_CameraAdapter.C
    HD_CoordSysCameraDataSceneIndex.C
    HD_CoordSysPrimSceneIndexPlugin.C
    HD_DependencySceneIndexPlugin.C
    HD_DependencyForwardingSceneIndexPlugin.C
    HD_DrawModeAdapter.C
    HD_HoudiniApexCharacterAPIAdapter.C
    HD_HoudiniApexCharacterBindingAPIAdapter.C
    HD_HoudiniApexSceneAdapter.C
    HD_HoudiniApexShapeBindingAPIAdapter.C
    HD_HoudiniApexShapeDeformAPIAdapter.C
    HD_HoudiniApexXformBindingAPIAdapter.C
    HD_HoudiniCameraPlateAPIAdapter.C
    HD_HoudiniFieldAssetAdapter.C
    HD_GeoConversionSceneIndexPlugin.C
    HD_HoudiniRendererPlugin.C
    HD_KarmaAtmosphereAdapter.C
    HD_KarmaSkyDomeLightAdapter.C
    HD_HoudiniLightBarnDoorAPIAdapter.C
    HD_HoudiniViewportGuideAPIAdapter.C
    HD_LightLinkingSceneIndexPlugin.C
    HD_MetaCurvesAdapter.C
    HD_MeshLightSceneIndex.C
    HD_MeshLightSceneIndexPlugin.C
    HD_HairDeformSchema.C
    HD_HairDeformAPIAdapter.C
    HD_HairDeformPointsDataSource.C
    HD_HairDeformPrimVarDataSource.C
    HD_HairDeformPrimVarsDataSource.C
    HD_HairDeformSceneIndex.C
    HD_HairDeformSceneIndexPlugin.C
    HD_HairDeformUtils.C
    HD_PortalLightSceneIndex.C
    HD_PortalLightSceneIndexPlugin.C
    HD_ScatterGenerativeProceduralPlugin.C
    HD_HdGpScatterEngine.C
    HD_HdGpScatterEngineUtils.C
    HD_HdGpHapiScatterEngine.C
    HD_HdGpHapiUtils.C
    HD_HdGpHapiPrimvarsDataSource.C
    HD_MotionBlurSceneIndexPlugin.C
)

